### ISSUE TITLE
Error executing on macOS

### ISSUE THREAD

**Issue by bramj** [cimm/codav#1]
Running `./codav` produces following error:
```
** (codav:87698): ERROR **: codav.vala:39: Unable to load file: Failed to open file “data/appmenu.ui”: No such file or directory
[1]    87698 trace trap  /Users/bram/Projects/codav/codav
```

**Comment by cimm** [comment]
There was an issue with the file being loaded via its relative path and not the absolute one. The CMake scirpt has been updated in 45c8ce95483545503e7992cc0438e0f087544f3c and should now be a bit smarter and install the `appmenu.ui` in the right directory.

The CMake installation should work now.

@bramj Can you try again with the updated instructions?

**Comment by bramj** [comment]
Sorry, no luck! Upon running `cmake .`, I get the following error:
```
CMake Error: File /Users/bram/Projects/codav/config.vala.cmake does not exist.
CMake Error at CMakeLists.txt:31 (configure_file):
  configure_file Problem configuring file
```

**Comment by cimm** [comment]
My bad, didn't notice I excluded the `config.vala.cmake` file in my `.gitignore`. Can you pull once more? Tried it on a clean Sierra machine and it seem to work now.
