### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by cimm** [cimm/codav#6]
It's currently using the default system icon, not nice. Need to design a nice SVG icon and add it to GResources.

Is there such a thing as open source icon designers?

**Comment by abmakko** [comment]
hello. sure there is such a thing as open source designers, and I happen to be one, This is a preview of a sample logo in a Gnome desktop environment.
![take a look-02](https://user-images.githubusercontent.com/36611833/38847857-7247ac8e-420c-11e8-8b07-93510888fafa.png)
![codav variation-05](https://user-images.githubusercontent.com/36611833/38885493-ce096d0e-427b-11e8-8d16-7f8a4a498669.png)

Have a look and tell me if you like it or any particular one, I also sent you a mail through your posted ad.

**Comment by abmakko** [comment]
![codav variation-05](https://user-images.githubusercontent.com/36611833/38885477-ba33824c-427b-11e8-8cb1-aa068b0b0678.png)

**Comment by cimm** [comment]
Wow, @abmakko thanks for reaching out. I did not expect someone would pass by and help out!

The ones with the lines make the most sense in my opinion, since a CODA file is basically just a list of transactions. I see why you went for the paper sheets but I think they are not as relevant sine most people won't print CODA files, they are meant for machine-to-machine consumption.

I personally like the monochrome ones the best (no a fan of the green colour scheme but hey... there's no accounting for taste as they say).

**Comment by abmakko** [comment]
okay no worries, I sent you the monochrome logo version in a pull request, since that is the one you prefer. cheers.

**Comment by abmakko** [comment]
google drive files of png and editable formats can be found [here](https://drive.google.com/drive/folders/19nOGZ4OQSs09uSUGCcHn1GbaH9NUX-4J)
